FROM openjdk:8u191-jre-alpine3.9

RUN apk add curl jq

#Workspace
WORKDIR /usr/share/babu

#add jar files
ADD target/selenium-docker.jar  selenium-docker.jar
ADD target/selenium-docker-tests.jar selenium-docker-tests.jar
ADD target/libs libs

#incase of dependencies, copy all .xls, .properties etc

#Add suit files
ADD book-flight-module.xml book-flight-module.xml
ADD search-module.xml   search-module.xml

#Add health check script
ADD healthcheck.sh healthcheck.sh

#BROWSER
#HUB_HOST
#MODULE
#ENTRYPOINT java -cp  selenium-docker.jar:selenium-docker-tests.jar:libs/* -DBROWSER=$BROWSER -DHUB_HOST=$HUB_HOST org.testng.TestNG $MODULE
ENTRYPOINT sh healthcheck.sh