version: "3"
services:
  hub: 
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
  
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    
  firefox: 
    image: selenium/node-firefox:3.141.59
    shm_size='1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub

  search-module:
    image: baaboo2u/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./search-result:/usr/share/babu/test-output